### PR TITLE
Fix broken headings in Markdown files

### PR DESCRIPTION
**Pull request by bryant1410**
GitHub changed the way Markdown headings are parsed, so this change fixes it.

See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.

Tackles bryant1410/readmesfix#1

### CODE REVIEW

**Comment by ivanseidel** [comment]
Change only what changed. Closing (as this is obviously not a human)

**Comment by bryant1410** [comment]
Sorry! :see_no_evil: This was affected by bryant1410/readmesfix#4 I'm a human!

human

**Comment by ivanseidel** [comment]
This should be affected only by persons. Not bots pretending to be real persons.

I'm really bad that you are doing this.. Is this just a way to get more commits and stats on github?

At least state on your pull request that it is an automated pull request. Don't make the github community worse with bots.

**Comment by bryant1410** [comment]
Hey. This was automated, yes. And I'm not trying to get more commits nor stats on GH. If I tried to get more stats on GH, I'd just add random old commits to public pointless repos.

Ok, maybe I could have stated this was automated, but I don't see how the community gets worse because of this. I'm just trying to fix repos after the GH breaking change.

**Comment by ivanseidel** [comment]
I see your point, but get my: We all hate spam on email, even thought they have something to offer.

When span is a obviously newsletter, we can filter. But when is a bot disguised, it's hard to tell the difference and know if the person really matter the subject.. In this case, I don't think you even know what is the purpose of this library if you didn't stopped by because of me replying to it...

Anyway, if you are doing this automated, it's called spam even if it's with the intention of something good. So, make sure to let people know that ;)

**Comment by bryant1410** [comment]
I disagree with the definition of spam :slightly_smiling_face: For me, spam is undesired email, regardless of it being automated or not.

And I could perfectly have created this PR manually without knowing the library, by just passing by (following a link or whatever) and seeing that the readme is broken.

Also, people know it's automated if they follow the first link.

**Comment by ivanseidel** [comment]
That would have been great, but as you could see, your "automation" didn't help at all. Will you still fix your PR? if not, let it be.

Just make sure to say it's automated if it's not you pushing the buttons.

**Pull request closed without merging**
